companies/urls.py
from django.conf.urls import url, patterns
from views import (ClientListView, ClientCreateView,
                ClientEditView, ClientDeleteView)


urlpatterns = patterns('',
    url(r'^clients/$', ClientListView.as_view(), name='clients_list'),
    url(r'^clients/new/$', ClientCreateView.as_view(), name='client_new'),
    url(r'^clients/(?P<pk>\d+)/$', ClientEditView.as_view(), name='client_edit'),
    url(r'^clients/(?P<pk>\d+)/delete/$', ClientDeleteView.as_view(), name='client_delete'),
)

main/urls.py
from django.conf.urls import url, patterns, include
from django.core.urlresolvers import reverse_lazy
from views import IndexView, login


urlpatterns = patterns('',
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^login/$', login, name="login"),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
          {"next_page" : reverse_lazy('login')}, name="logout"),
)

supplychain/urls.py
from django.conf.urls import patterns, include, url, RegexURLResolver, RegexURLPattern
from django.contrib import admin
from django.contrib.auth.decorators import permission_required, login_required
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'supplychain.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('main.urls')),
    url(r'^warehouse/', include('warehouse.urls')),
    url(r'^companies/', include('companies.urls')),
    url(r'^orders/', include('orders.urls')),
)

def traverse(patterns):
    for pattern in patterns:
        if isinstance(pattern, RegexURLResolver):
            traverse(pattern.url_patterns)
        elif isinstance(pattern, RegexURLPattern):
            callback = pattern.callback
            perms = settings.URL_PERMISSIONS.get(pattern.name, None)
            if perms and len(perms) > 0:
                pattern._callback = permission_required(perm=perms, raise_exception=True)(callback)
                pattern._callback = login_required(pattern.callback)

traverse(urlpatterns)
#settings.URL_PERMISSIONS

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

companies/models.py
from django.db import models
from django.db.utils import IntegrityError
from django.contrib.auth.models import AbstractUser, UserManager, UserManager
from constants import *

# Create your models here.
class Company(models.Model):
    name = models.CharField(max_length=64, verbose_name='Firma nomi')
    address = models.CharField(max_length=64, blank=True, null=True, verbose_name='Manzil')
    telephone = models.CharField(max_length=64, blank=True, null=True,
                                 verbose_name='Telefon', help_text='vergul bilan yozilsin')
    client_type = models.IntegerField(choices=CLIENT_TYPES, default=CLIENT_DILER,
                                 verbose_name='Klient turi')

    class Meta:
        permissions = (
                ("read_company", "Can read company list"),
        )

    def __unicode__(self):
        return '%s' % (self.name)

class CustomUserManager(UserManager):
    def get_queryset(self, *args, **kwargs):
        queryset = super(CustomUserManager, self).get_queryset(*args, **kwargs)
        queryset = queryset.select_related('company')
        return queryset

class User(AbstractUser):
    company = models.OneToOneField(Company, blank=True, null=True)
    is_comp_owner = models.BooleanField(default=False)

    # def has_perm(self, perm, obj=None):
    #     res = super(User, self).has_perm(perm, obj)
    #     print res, perm, self
    #     return res

    def save(self, *args, **kwargs):
        if self.is_superuser in (None, False) and self.company is None:
            raise IntegrityError('every user must belong to company, except superuser')
        super(User, self).save(*args, **kwargs)

    def __unicode__(self):
        return '%s %s (%s)' % (self.first_name, self.last_name, self.username)

# for some reason we dont have multiple company handling yet
# thats why we need to get hard coded company
# basically first one is MAIN company
def get_main_company():
    main_company = Company.objects.all().order_by('pk')[0]
    return main_company

companies/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext, ugettext_lazy as _
from models import User

class UserCreationForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, from the given username and
    password.
    """
    error_messages = {
        'duplicate_username': _("A user with that username already exists."),
        'password_mismatch': _("The two password fields didn't match."),
    }
    username = forms.RegexField(label=_("Username"), max_length=30,
        regex=r'^[\w.@+-]+$',
        help_text=_("Required. 30 characters or fewer. Letters, digits and "
                    "@/./+/-/_ only."),
        error_messages={
            'invalid': _("This value may contain only letters, numbers and "
                         "@/./+/-/_ characters.")})
    password1 = forms.CharField(label=_("Password"),
        widget=forms.PasswordInput)
    password2 = forms.CharField(label=_("Password confirmation"),
        widget=forms.PasswordInput,
        help_text=_("Enter the same password as above, for verification."))

    class Meta:
        model = User
        fields = ("username",)

    def clean_username(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM. See #13147.
        username = self.cleaned_data["username"]
        try:
            User._default_manager.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError(
            self.error_messages['duplicate_username'],
            code='duplicate_username',
        )

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

companies/views.py
from django.shortcuts import render
from django.contrib.auth.models import Permission
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.views.generic import (TemplateView, ListView, CreateView,
                                UpdateView, DeleteView)
from django.views.generic.detail import SingleObjectMixin
from django.db import transaction
from django.db.utils import IntegrityError
from django import forms
from core.views import BaseSupplyChainViewMixin
from models import User, Company, CLIENT_TYPES

from main.permissions import CLIENT_PERMISSIONS

# Create your views here.
class ClientListView(BaseSupplyChainViewMixin, ListView):
    template_name = 'companies/clients.html'
    # first company is MAIN company
    queryset = Company.objects.all().order_by('pk')[1:]


class ClientForm(forms.ModelForm):
    telephone= forms.CharField(widget=forms.Textarea,label='Telefon',
                               required=False,
                               help_text='vergul bilan yozilsin. Mn:+99890 100-00-00, +99890 100-00-01')
    username = forms.CharField(max_length=16, label='Foydalanuvchi nomi')
    password = forms.CharField(widget=forms.PasswordInput, required=False,
                               label='Parol')

    class Meta:
        model = Company

    def __init__(self, *args, **kwargs):
        if kwargs.get('instance'):
            initial = {}
            initial['username'] = kwargs['instance'].user.username
            kwargs['initial'] = initial
        return super(ClientForm, self).__init__(*args, **kwargs)

    def clean_phone(self):
        '''
        phone numbers could be given by comma, new line, space
        we should save them using new lines
        '''
        telephone = self.cleaned_data.get('telephone', '')
        phones = telephone.replace(',', '\n').split()
        return ',\n'.join(phones)


class ClientCreateView(BaseSupplyChainViewMixin,
                       CreateView):
    template_name = 'companies/client_edit.html'
    form_class = ClientForm
    model = Company
    success_url = reverse_lazy('clients_list')

    def form_valid(self, form):
        username     = form.cleaned_data['username']
        password     = form.cleaned_data.get('password', None)
        company_name = form.cleaned_data['name']
        telephone    = form.cleaned_data['telephone']
        address      = form.cleaned_data['address']
        client_type  = form.cleaned_data['client_type']
        with transaction.atomic():
            comp = Company.objects.create(name=company_name, address=address,
                                   client_type=client_type,
                                   telephone=telephone)
            usr = User.objects.create_user(username=username,
                                           password=password,
                                           company=comp)
            perms = Permission.objects.filter(codename__in=CLIENT_PERMISSIONS)
            usr.user_permissions.add(*perms)
        return HttpResponseRedirect(self.success_url)

    def post(self, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            try:
                return self.form_valid(form)
            except IntegrityError as e:
                form.add_error(field=None, error=e.message)

        return self.form_invalid(form)


class ClientEditView(BaseSupplyChainViewMixin,
                    UpdateView):
    template_name = 'companies/client_edit.html'
    form_class = ClientForm
    model = Company
    success_url = reverse_lazy('clients_list')

    def form_valid(self, form):
        username     = form.cleaned_data['username']
        password     = form.cleaned_data.get('password', None)
        company_name = form.cleaned_data['name']
        telephone    = form.cleaned_data['telephone']
        address      = form.cleaned_data['address']
        client_type  = form.cleaned_data['client_type']
        with transaction.atomic():
            company = self.object
            company.telephone = telephone
            company.name = company_name
            company.address = address
            company.client_type = client_type
            user = company.user
            user.username = username
            if password:
                user.set_password(password)
            user.save()
            company.save()

        return HttpResponseRedirect(self.success_url)


class ClientDeleteView(BaseSupplyChainViewMixin,
                       DeleteView):
    template_name = 'companies/client_delete.html'
    model = Company
    success_url = reverse_lazy('clients_list')

companies/templates/companies/client_delete.html
{% extends "warehouse/base_warehouse.html" %}
{% load bootstrap3 %}

{% block content %}
  <h3>Klientni o'chirib tashlash</h3>
  <p><b>{{company}}</b> ni o'chirishni tasdiqlaysizmi?</p>
  <form class="form" action="{% url "client_delete" pk=company.id %}" method="POST">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Ha." />
    <a href="{% url "clients_list" %}" class="btn btn-primary">Yo'q</a>
  </form>

{% endblock %}

companies/templates/companies/client_edit.html
{% extends "warehouse/base_warehouse.html" %}
{% load bootstrap3 %}

{% block content %}
  <div class="row">
    <form action="
    {% if company %}
        {% url "client_edit" pk=company.id %}
    {% else %}
        {% url "client_new" %}
    {% endif %}
    " method="post" class="form col-xs-8">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% buttons %}
              <button type="submit" class="btn btn-primary">
                  Xotiraga saqlash
              </button>
          {% endbuttons %}
    </form>
  </div>

  {% if company %}
  <div class="row">
    <div class="col-xs-8 table-responsive">
      <table class="table table-hover table-bordered">
        <caption>Ombor holati</caption>
        <thead>
          <tr>
            <th width="25%">Mahsulot</th>
            <th width="25%">Miqdori</th>
          </tr>
        </thead>
        <tbody>
        {% for product in company.warehouse.state %}
          <tr>
            <td>{{product.name}}</td>
            <td>{{product.quantity}}</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  {% endif %}
{% endblock %}

companies/templates/companies/clients.html
{% extends "warehouse/base_warehouse.html" %}

{% block content %}

  <div class="row">
    <div class="table-responsive">
      <table class="table table-hover table-bordered">
        <caption>Klientlar</caption>
        <thead>
          <tr>
            <th>Nomi</th>
            <th>Manzil</th>
            <th>Telefon</th>
            <th>Klient turi</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        {% for company in company_list %}
          <tr>
            <td><a href="{% url "client_edit" pk=company.id%}">{{company.name}}</a></td>
            <td>{{company.address}}</td>
            <td>{{company.telephone}}</td>
            <td width="15%">
              {% if company.client_type == 0 %}
                <span class="label label-success">Diler</span>
              {% elif company.client_type == 1%}
                <span class="label label-primary">Bozor</span>
              {% elif company.client_type == 2%}
                <span class="label label-warning">Do'kon</span>
              {% endif %}
            </td>
            <td width="5%">
              <a href="{% url "client_edit" pk=company.id%}"><span class="glyphicon glyphicon-edit"/></a>
              <a href="{% url "client_delete" pk=company.id%}"><span class="glyphicon glyphicon-trash"/></a>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>

  </div>
  <a href="{% url "client_new" %}" class="btn btn-primary">Yangi</span></a>
{% endblock %}