main/urls.py
from django.conf.urls import url, patterns, include
from django.core.urlresolvers import reverse_lazy
from views import IndexView, login


urlpatterns = patterns('',
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^login/$', login, name="login"),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
          {"next_page" : reverse_lazy('login')}, name="logout"),
)

supplychain/urls.py
from django.conf.urls import patterns, include, url, RegexURLResolver, RegexURLPattern
from django.contrib import admin
from django.contrib.auth.decorators import permission_required, login_required
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'supplychain.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('main.urls')),
    url(r'^warehouse/', include('warehouse.urls')),
    url(r'^companies/', include('companies.urls')),
    url(r'^orders/', include('orders.urls')),
)

def traverse(patterns):
    for pattern in patterns:
        if isinstance(pattern, RegexURLResolver):
            traverse(pattern.url_patterns)
        elif isinstance(pattern, RegexURLPattern):
            callback = pattern.callback
            perms = settings.URL_PERMISSIONS.get(pattern.name, None)
            if perms and len(perms) > 0:
                pattern._callback = permission_required(perm=perms, raise_exception=True)(callback)
                pattern._callback = login_required(pattern.callback)

traverse(urlpatterns)
#settings.URL_PERMISSIONS

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

warehouse/urls.py
from django.conf.urls import url, include, patterns
from views import (ProductListView, ProductEditView, ProductCreateView,
                   ProductDeleteView, CategoryListView, CategoryEditView,
                   CategoryCreateView, CategoryDeleteView, WarehouseHistoryView,
                   WarehouseDashboardView)


urlpatterns = patterns('',
    url(r'^products/$', ProductListView.as_view(), name='warehouse_products'),
    url(r'^products/(?P<pk>\d+)/$', ProductEditView.as_view(), name='warehouse_product_edit'),
    url(r'^products/new/$', ProductCreateView.as_view(), name='warehouse_product_new'),
    url(r'^products/(?P<pk>\d+)/delete/$', ProductDeleteView.as_view(), name='warehouse_product_delete'),

    url(r'^categories/$', CategoryListView.as_view(), name='warehouse_categories'),
    url(r'^categories/(?P<pk>\d+)/$', CategoryEditView.as_view(), name='warehouse_category_edit'),
    url(r'^categories/new/$', CategoryCreateView.as_view(), name='warehouse_category_new'),
    url(r'^categories/(?P<pk>\d+)/delete/$', CategoryDeleteView.as_view(), name='warehouse_category_delete'),

    url(r'^history/$', WarehouseHistoryView.as_view(), name='warehouse_history'),
    url(r'^dashboard/$', WarehouseDashboardView.as_view(), name='warehouse_dashboard'),
)

warehouse/models.py
from django.db import models, transaction
from django.db.utils import IntegrityError
from django.db.models.signals import post_save
from django.dispatch import receiver
from companies.models import Company
from warehouse.constants import *

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=32, verbose_name='Nomlanish', unique=True)

    class Meta:
        permissions = (
                ("read_category", "Can read category data"),
        )

    def __unicode__(self):
        return self.name

class ProductManager(models.Manager):
    def externals(self):
        return self.get_queryset() \
                    .filter(internal=False)

class Product(models.Model):
    name = models.CharField(max_length=32, verbose_name='Nomlanish', unique=True)
    description = models.TextField(blank=True, null=True, verbose_name="Ma'lumot")
    category = models.ForeignKey(Category, verbose_name='Kategoriya')
    internal = models.BooleanField(default=False, verbose_name='Ichki',help_text='products for internal use only, will not be shown to customer')

    objects = ProductManager()

    class Meta:
        permissions = (
                ("read_product", "Can read product data"),
        )

    def __unicode__(self):
        return self.name


class Stock(models.Model):
    product = models.ForeignKey('Product')
    warehouse = models.ForeignKey('Warehouse')
    quantity = models.FloatField()
    created = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return '%s(%s)' % (self.product.name, str(self.quantity))

    class Meta:
        abstract = True

class WarehouseTransaction(Stock):
    '''
    product quantity added/removed to/from warehouse
    '''
    stock_type = models.IntegerField(choices=STOCK_TYPES, default=0,
                                     help_text='added or removed from warehouse',
                                     db_index=True)

    @transaction.atomic
    def save(self, *args, **kwargs):
        '''
        kind of app.level trigger when products added/removed to/from stock
        change the counter of warehouse stock if not available create it
        WHY ATOMIC? when in parallel users add or remove items
        this will create inconsistency in the app
        '''
        if not self.quantity:
            # do not save transactions with zero quantity
            return

        super(WarehouseTransaction, self).save(*args, **kwargs)
        try:
            stock = WarehouseStock.objects \
                                .filter(warehouse_id=self.warehouse_id) \
                                .get(product_id=self.product_id)
        except WarehouseStock.DoesNotExist:
            stock = WarehouseStock(product=self.product, warehouse=self.warehouse,
                                   quantity=0)

        quantity = stock.quantity
        if self.stock_type == STOCK_ADD:
            stock.quantity = quantity + self.quantity
        else: # STOCK_DEL
            stock.quantity = quantity - self.quantity
            if stock.quantity < 0:
                raise IntegrityError('Omborda "%s"dan %s ta mavjud, lekin %s ta so\'ralmoqda' % (self.product,quantity, self.quantity))
        stock.save()

class WarehouseStock(Stock):
    '''
    product quantity in warehouse
    same as above difference is this WarehouseStock defines how many products
    are in particular warehouse, WarehouseTransaction defines when
    added or removed item from stock
    NOTE: only WarehouseTransaction can create/update fields in this table
    '''

    def __unicode__(self):
        return '%s(%s)' % (self.product.name, str(self.quantity))

class Warehouse(models.Model):
    company = models.OneToOneField(Company) # for now, only one warehouse for each company
    name = models.CharField(max_length=32)
    stocks = models.ManyToManyField(Product, through='WarehouseStock',
                                      through_fields=('warehouse', 'product'),
                                      related_name='stocks')

    class Meta:
        permissions = (
                ("read_warehouse", "Can read warehouse data"),
        )

    def __unicode__(self):
        return self.name

    def totals(self):
        totals = {}
        for stock in self.warehousestock_set.all():
            totals[stock.product] = stock.quantity
        return totals

    def state(self):
        product_state = []
        available_products = set()
        for stock in self.warehousestock_set.all().select_related('product'):
            product_state.append({'name':stock.product.name,
                                 'quantity':stock.quantity,
                                 'internal':stock.product.internal,
                                 'pk':stock.product.pk})
            available_products.add(stock.product.pk)

        # add not available products as zero value
        for product in Product.objects.filter(~models.Q(pk__in=available_products)):
            product_state.append({'name':product.name,
                                 'quantity':0,
                                 'internal':product.internal,
                                 'pk':product.pk})
        return product_state

    def add_item(self, product, quantity):
        kwargs = {'stock_type':STOCK_ADD,
                 'quantity':quantity,
                 'product':product,
                 'warehouse':self}
        wtx = WarehouseTransaction(**kwargs)
        wtx.save()
        return wtx

    def take_item(self, product, quantity):
        kwargs = {'stock_type':STOCK_DEL,
                 'quantity':quantity,
                 'product':product,
                 'warehouse':self}
        wtx = WarehouseTransaction(**kwargs)
        wtx.save()
        return wtx


@receiver(post_save, sender=Company)
def company_creation_handler(sender, instance, created, **kwargs):
    if not created:
        return

    data = {'company':instance,
            'name':'main_warehouse'}
    wr = Warehouse.objects.create(**data)

warehouse/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse, reverse_lazy
from django.views.generic import (ListView, View, TemplateView,
                                  UpdateView, CreateView, DeleteView)
from django.forms import models as model_forms
from django.contrib import messages
from django.db.utils import IntegrityError
from django.core.exceptions import ValidationError
from core.views import BaseSupplyChainViewMixin
from models import (Product, Category, WarehouseTransaction,
                    STOCK_ADD, STOCK_DEL, WarehouseStock)
from companies.models import get_main_company

# Create your views here.
# Products
class ProductListView(BaseSupplyChainViewMixin, ListView):
    template_name = 'warehouse/products.html'
    model = Product

class ProductEditView(BaseSupplyChainViewMixin, UpdateView):
    template_name = 'warehouse/product_edit.html'
    model = Product
    success_url = reverse_lazy('warehouse_products')

class ProductCreateView(BaseSupplyChainViewMixin, CreateView):
    template_name = 'warehouse/product_edit.html'
    model = Product
    success_url = reverse_lazy('warehouse_products')

    def form_valid(self, form):
        res = super(ProductCreateView, self).form_valid(form)
        warehouse = self.request.user.company.warehouse
        stock = WarehouseStock(product=self.object, warehouse=warehouse,
                                   quantity=0)
        stock.save()
        return res

class ProductDeleteView(BaseSupplyChainViewMixin, DeleteView):
    template_name = 'warehouse/product_delete.html'
    model = Product
    success_url = reverse_lazy('warehouse_products')

# Categories
class CategoryListView(BaseSupplyChainViewMixin, ListView):
    template_name = 'warehouse/categories.html'
    model = Category

class CategoryEditView(BaseSupplyChainViewMixin, UpdateView):
    template_name = 'warehouse/category_edit.html'
    model = Category
    success_url = reverse_lazy('warehouse_categories')

class CategoryCreateView(BaseSupplyChainViewMixin, CreateView):
    template_name = 'warehouse/category_edit.html'
    model = Category
    success_url = reverse_lazy('warehouse_categories')

class CategoryDeleteView(BaseSupplyChainViewMixin, DeleteView):
    template_name = 'warehouse/category_delete.html'
    model = Category
    success_url = reverse_lazy('warehouse_categories')

class WarehouseHistoryView(BaseSupplyChainViewMixin, ListView):
    template_name = 'warehouse/history.html'
    queryset = WarehouseTransaction.objects.all().order_by('-created')
    paginate_by = 20

    def get_queryset(self, *args, **kwargs):
        queryset = super(WarehouseHistoryView, self).get_queryset(*args, **kwargs)
        queryset = queryset.select_related('product')
        q = queryset.filter(warehouse=self.request.user.company.warehouse.id)
        return q

class WarehouseDashboardView(BaseSupplyChainViewMixin, TemplateView):
    template_name = 'warehouse/dashboard.html'
    add_prefix = 'add_'
    del_prefix = 'del_'
    success_url = reverse_lazy('warehouse_dashboard')

    def get_context_data(self, **kwargs):
        context = super(WarehouseDashboardView, self).get_context_data(**kwargs)
        user = self.request.user
        warehouse = user.company.warehouse
        context['products'] = warehouse.state()
        main_company = get_main_company()
        context['is_main'] = user.company == main_company
        return context

    def post(self, *args, **kwargs):
        POST = self.request.POST.copy()
        warehouse = self.request.user.company.warehouse
        # (product_id, quantity)
        apfx_len = len(self.add_prefix)
        rpfx_len = len(self.del_prefix)
        add = []
        remove = []
        internal_products = Product.objects.filter(internal=True).values_list('pk', flat=True)
        for k,v in POST.items():
            if not v:
                continue

            if k.startswith(self.add_prefix):
                add.append( ( int(k[apfx_len:]), int(v) ) )
            elif k.startswith(self.del_prefix):
                remove.append( ( int(k[rpfx_len:]), int(v) ) )

        add = filter(lambda x:x[0] not in internal_products, add)
        remove = filter(lambda x:x[0] not in internal_products, remove)

        for item in add:
            WarehouseTransaction \
                .objects \
                .create(product_id=item[0],
                        warehouse_id=warehouse.id,
                        quantity=item[1],
                        stock_type=STOCK_ADD)

        for item in remove:
            try:
                WarehouseTransaction \
                    .objects \
                    .create(product_id=item[0],
                            warehouse_id=warehouse.id,
                            quantity=item[1],
                            stock_type=STOCK_DEL)
            except IntegrityError as ie:
                messages.error(self.request, ie.message)

        if messages:
            return self.get(self.request, *args, **kwargs)

        return HttpResponseRedirect(self.success_url)

warehouse/templates/warehouse/base_warehouse.html
{% extends "core/base.html" %}
{% load staticfiles %}

warehouse/templates/warehouse/categories.html
{% extends "warehouse/base_warehouse.html" %}

{% block content %}

  <div class="row">
    <div class="table-responsive col-lg-6">
      <table class="table table-hover table-bordered">
        <caption>Kategoriyalar</caption>
        <thead>
          <tr>
            <th>#</th>
            <th>Nomlanishi</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        {% for category in category_list %}
          <tr>
            <th scope="row" width="5%">{{category.id}}</th>
            <td>{{category.name}}</td>
            <td width="15%">
              <a href="{% url "warehouse_category_edit" pk=category.id%}"><span class="glyphicon glyphicon-edit"/></a>
              <a href="{% url "warehouse_category_delete" pk=category.id%}"><span class="glyphicon glyphicon-trash"/></a>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>

  </div>
  <a href="{% url "warehouse_category_new" %}" class="btn btn-primary">Yangi</span></a>
{% endblock %}

warehouse/templates/warehouse/category_delete.html
{% extends "warehouse/base_warehouse.html" %}
{% load bootstrap3 %}

{% block content %}
  <h3>Kategoriyani o'chirish</h3>
  <p><b>{{ category }}</b> ni o'chirishni tasdiqlaysizmi?</p>
  <form class="form" action="{% url "warehouse_category_delete" pk=category.id %}" method="POST">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Ha." />
    <a href="{% url "warehouse_categories" %}" class="btn btn-primary">Yo'q</a>
  </form>

{% endblock %}

warehouse/templates/warehouse/category_edit.html
{% extends "warehouse/base_warehouse.html" %}
{% load bootstrap3 %}

{% block content %}
    <form action="
      {% if category %}
        {% url "warehouse_category_edit" pk=category.id %}
      {% else %}
        {% url "warehouse_category_new" %}
      {% endif %}
      " method="post" class="form">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% buttons %}
              <button type="submit" class="btn btn-primary">
                  Xotiraga saqlash
              </button>
          {% endbuttons %}
    </form>
{% endblock %}

warehouse/templates/warehouse/dashboard.html
{% extends "warehouse/base_warehouse.html" %}
{% load staticfiles %}


{% block content %}
<form action="{% url "warehouse_dashboard" %}" method="POST" class="form">
{% csrf_token %}
    <div class="row">
    <div class="table-responsive">
      {% if messages %}
      {% for message in messages %}
        <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        {{message}}
        </div>
      {% endfor %}
      {% endif %}
      <table class="table table-hover table-bordered">
        <caption>Ombor holati</caption>
        <thead>
          <tr>
            <th width="25%">Mahsulot</th>
            <th width="25%">Miqdori</th>
            {% if is_main %}
            <th width="5%">Ichki</th>
            {% endif %}
            <th style="min-width: 5em">Kirim</th>
            <th style="min-width: 5em">Chiqim</th>
          </tr>
        </thead>
        <tbody>
        {% for product in products %}
          <tr>
            {% if is_main or not product.internal %}
            <td>{{product.name}}</td>
            <td>{{product.quantity}}</td>
            {% if is_main %}
            <td class="text-center">
              {% if product.internal %}
                <span class="glyphicon glyphicon-ok"/>
              {% endif %}
            </td>
            {%endif%}
            <td>
              <input class="form-control" maxlength="64" name="add_{{product.pk}}" placeholder="0" type="number" value="">
            </td>
            <td>
              <input class="form-control" maxlength="64" name="del_{{product.pk}}" placeholder="0" type="number" value="">
            </td>
            {% endif %}
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>

  </div>
  <div class="row">
    <button type="submit" class="btn btn-primary">
        Xotiraga saqlash
    </button>
  </div>
</form>
{% endblock %}

warehouse/templates/warehouse/history.html
{% extends "warehouse/base_warehouse.html" %}
{% load staticfiles %}
{% load query_transform %}

{% block content %}
    <div class="row">
    <div class="table-responsive col-lg-6">
      <table class="table table-hover table-bordered">
        <caption>Ombor tarixi</caption>
        <thead>
          <tr>
            <th>Mahsulot</th>
            <th>Miqdor</th>
            <th>Sana</th>
            <th>Kirim/Chiqim</th>
          </tr>
        </thead>
        <tbody>
        {% for transaction in object_list %}
          <tr>
            <td>{{transaction.product.name}}</th>
            <td>{{transaction.quantity}}</td>
            <td>{{transaction.created|date:"d-m-Y G:i"}}</td>
            <td width="5%" class="text-center">
              {% if transaction.stock_type == 0%}
                <span class="label label-success">+</span>
              {% else %}
                <span class="label label-danger">-</span>
              {% endif %}
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>

  </div>

  <nav>
    <ul class="pagination">
      <li>
        <a href="?{% query_transform request page=1 %}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% for num in pages %}
      <li class="{% if num == page_obj.number %}active{% endif %}">
          <a href="?{% query_transform request page=num %}">{{num}}</a>
      </li>
      {% endfor %}
      <li>
        <a href="?{% query_transform request page=last_page %}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
    </ul>
  </nav>
{% endblock %}

warehouse/templates/warehouse/product_delete.html
{% extends "warehouse/base_warehouse.html" %}
{% load bootstrap3 %}

{% block content %}
  <h3>Mahsulotni o'chirish</h3>
  <p><b>{{ product }}</b> ni o'chirishni tasdiqlaysizmi?</p>
  <form class="form" action="{% url "warehouse_product_delete" pk=product.id %}" method="POST">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Ha." />
    <a href="{% url "warehouse_products" %}" class="btn btn-primary">Yo'q</a>
  </form>

{% endblock %}

warehouse/templates/warehouse/product_edit.html
{% extends "warehouse/base_warehouse.html" %}
{% load bootstrap3 %}

{% block content %}
    <form action="
      {% if product %}
        {% url "warehouse_product_edit" pk=product.id %}
      {% else %}
        {% url "warehouse_product_new" %}
      {% endif %}
      " method="post" class="form">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% buttons %}
              <button type="submit" class="btn btn-primary">
                  Xotiraga saqlash
              </button>
          {% endbuttons %}
    </form>
{% endblock %}

warehouse/templates/warehouse/products.html
{% extends "warehouse/base_warehouse.html" %}

{% block content %}

  <div class="row">
    <div class="table-responsive col-lg-6">
      <table class="table table-hover table-bordered">
        <caption>Mahsulotlar</caption>
        <thead>
          <tr>
            <th>#</th>
            <th>Nomlanishi</th>
            <th>Ichki</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        {% for product in product_list %}
          <tr>
            <th scope="row" width="5%">{{product.id}}</th>
            <td>{{product.name}}</td>
            <td width="10%" class="text-center">
              {% if product.internal %}
                <span class="glyphicon glyphicon-ok"/>
              {% endif %}
            </td>
            <td width="15%">
              <a href="{% url "warehouse_product_edit" pk=product.id%}"><span class="glyphicon glyphicon-edit"/></a>
              <a href="{% url "warehouse_product_delete" pk=product.id%}"><span class="glyphicon glyphicon-trash"/></a>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>

  </div>
  <a href="{% url "warehouse_product_new" %}" class="btn btn-primary">Yangi</span></a>
{% endblock %}

warehouse/templates/warehouse/stock.html
{% extends "warehouse/base_warehouse.html" %}
{% load bootstrap3 %}

{% block content %}
    <form action="{% url "warehouse_stock_transaction" %}" method="post" class="form">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% buttons %}
              <button type="submit" class="btn btn-primary">
                  Xotiraga saqlash
              </button>
          {% endbuttons %}
    </form>
{% endblock %}